### ISSUE TITLE
PlantUML usage

### ISSUE THREAD

**Issue by berezovskyi** [marcelhuberfoo/docker-pandoc-gitit#1]
Hello Marcel,

Thank you for your work and publishing this docker image! I was trying to find if you included any filters for plantuml but couldn't see any. How do you integrate it into your workflow?

Best regards,
Andrew

**Comment by marcelhuberfoo** [comment]
Hi Andrew,

You are right, filters for plantuml are not included. Neither for gitit nor for pandoc. Check out https://github.com/jgm/pandocfilters for a set of available pandoc filters and examples how to use them. The versions I use are based on them but slightly modified. Python filters - currently without plantuml - reside in /filters. Probably I will add some gitit plugins I use to a folder /plugins.
I will extend the docs to show the usage too.

Thank you for your feedback and regards,
 marcel

**Comment by berezovskyi** [comment]
Thanks a lot for quick reply!
