### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by oupala** [marcelhuberfoo/docker-pandoc-gitit#2]
I used this [commande](/marcelhuberfoo/docker-pandoc-gitit#gitit) in order to get a preview of gitit and its features. But I can't figure out how to use it.

I can't access the web interface on port 5001 (no answer).

I don't know what to do.

Any help is welcome!

**Comment by marcelhuberfoo** [comment]
I guess you chose the wrong port. Try to access it at `60000` as the command you mentioned is forwarding requests on your localhost port `60000` to the container port `5001`.
The following directive needs to be changed in order to work as you expected: `-p 5001:5001`

**Comment by oupala** [comment]
How could I have missed that! Thanks @marcelhuberfoo for your answer.

Maybe I read [this paragraph](https://github.com/marcelhuberfoo/docker-pandoc-gitit#exposed-ports) that say that 5001 is the exposed port.

> Exposed Ports
> 5001: Gitit default webserver port

 Maybe you can change to say that 5001 is the port exposed on port 6000.

Now I can see that the container is starting and then stopping. `docker logs` tells me that the container stops after printing the pandoc help on the console.

Why is the gitit startup command [replaced](/marcelhuberfoo/docker-pandoc-gitit/blob/83afb88ea6287fe44dfddce9e2f0c162c63528a1/Dockerfile#L32) by the pandoc command ?

``` Dockerfile
#CMD ["gitit", "-f", "/data/gitit.conf"]
CMD ["pandoc", "--help"]
```

**Comment by marcelhuberfoo** [comment]
Hi @oupala 
The container can be used two-fold, either as pandoc document converter - which is in fact the default - or as gitit server.
Aha, I just noticed the mistake in the printed command to start the gitit server and will correct it soon.
Append `gitit -f /data/gitit.conf` to the command printed to start the server.
